apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
  - image: ${K8S_IMAGE}
deploy:
  kubectl:
    manifests:
      - manifest.k8s*.yaml
    flags:
      apply: ["--prune", "-l", "project=${K8S_PROJECT}"]
